### PR TITLE
Adding if condition to prevent null pointer exception

### PR DESCRIPTION
**Pull request by ufuk-gr4vy**
Adding replace.sh to update utils.go file with if condition to prevent null pointer exception

### CODE REVIEW

**Review by phillipgr4vy — APPROVED** [review]

**Comment by cbetta** [comment]
@

**Review by cbetta — CHANGES_REQUESTED** [review]
Please use a replace.sh file.

**Review by cbetta — APPROVED** [review]

**Review by cbetta — DISMISSED** [review]
Actually @danielknell is right

**Review by danielknell — APPROVED** [review]
👍

**Pull request merged**
